<a href="https://colab.research.google.com/github/tombro27/Gradient-Descent/blob/main/Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Generating Data


In [ ]:
X= 5*np.random.rand(1000,1)
y= 8 + 7*X + np.random.rand(1000,1)

The Normal Equation


In [ ]:
X_ =np.c_[np.ones((1000,1)),X]
params=np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)

In [ ]:
params

array([[8.5226705 ],
       [6.99172065]])

SVD

In [ ]:
params_svd = np.linalg.pinv(X_).dot(y)

In [ ]:
params_svd

array([[8.5226705 ],
       [6.99172065]])

Batch GD


In [ ]:
eta = 0.1
iters = 10000
m=1000
W=np.random.rand(2,1)
for i in range(iters):
  gradient = 2/m * X_.T.dot(X_.dot(W)-y)
  W-=eta*gradient

In [ ]:
W

array([[8.5226705 ],
       [6.99172065]])

SGD

In [ ]:
n_epochs =50
t0 ,t1 =5,50

In [ ]:
def learning_schedule (t):
  return t0/(t+t1)

In [ ]:
W_SGD=np.random.rand(2,1)

In [ ]:
for epoch in range(n_epochs):
  for i in range(m):
    eta=learning_schedule(epoch*m+i)
    instance=np.random.randint(m)
    xi=X_[instance:instance+1]
    yi=y[instance:instance+1]
    gradient=2*xi.T.dot(xi.dot(W_SGD)-yi)
    W_SGD-=eta*gradient

In [ ]:
W_SGD

array([[8.52063444],
       [6.99390268]])

In [ ]:
n_epochs =4000
t0 ,t1 =10000,100000
size = int(m/100)
W_MGD=np.random.rand(2,1)
t=1
for epoch in range(n_epochs):
  indices=np.random.permutation(m)
  X_shuffled=X_[indices]
  y_shuffled=y[indices]
  for i in range(0,m,size):
    eta=learning_schedule(t)
    xi=X_[instance:instance+size]
    yi=y[instance:instance+size]
    gradient=2/size*xi.T.dot(xi.dot(W_MGD)-yi)
    W_MGD-=eta*gradient
    t+=1

In [ ]:
W_MGD

array([[8.44485715],
       [6.97890454]])